fix(fs.c, windows, ucrt64): fix getcwd for windows ucrt64 builds
DarkPlacesEngine/DarkPlaces pull request #214
Opened 2024-10-20 09:07 UTC by NaitLee

I'm really late 🥲 With this patch, compiling darkplaces master with msys2 ucrt64 environment is back to normal.

Closes [gitlab.com/xonotic/darkplaces#422](https://gitlab.com/xonotic/darkplaces/-/issues/422).

2024-10-20 09:12 UTC, hemebond approved these changes

2024-10-25 11:12 UTC, divVerent approved these changes

2024-10-25 11:16 UTC, divVerent requested changes

2024-10-25 13:23 UTC, NaitLee commented on fs.c
> +		GetCurrentDirectoryW(sizeof(fs_basedirw), fs_basedirw);
You are right. New commit pushed to fix this.

2024-10-25 17:25 UTC, divVerent approved these changes

2024-10-25 17:27 UTC, divVerent commented
wasm error seems unrelated.

As for _wgetcwd vs GetCurrentDirectoryW - I still am not convinced _that_ was the problem, but at the same time, don't care. The winapi function name is slightly more readable than the not-really-posix name, both are proprietary, so may as well keep the winapi one you got there.

2024-10-25 17:27 UTC, merged