Fix several long-lasting font rendering problems
DarkPlacesEngine/darkplaces pull request #67
Opened 2023-01-29 09:02 UTC by NaitLee

This patch is effort of half one year and more than 3 trials by 2 persons.

Several big problems in font rendering (`ft2`) were solved. Read more below.

Before merging, it is wise to look into the [code](https://github.com/NaitLee/darkplaces/tree/NaitLee/ft2-better-maps-for-bigblock-chars) and [give it some test](https://github.com/NaitLee/darkplaces/releases/tag/patch-snapshot-0) first.

----

**Patch summary:**

- Fix the overall problem stated in #49 with the idea “incremental maps”
  - New API `Font_GetMapForChar` for better support, mostly because `mapch` can be dynamic; `FontMap_FindForChar` and `Font_LoadMapForIndex` become legacy, but still can be used (without `incmap` support, behaves as usual)
  - The new CVar `r_font_disable_incmaps` for always using old mapping behavior, useful for e.g. comparing the before/after of this fix
- Fix the problem stated in #65
  - `float kerning[256][256]` in `struct ft2_font_map_s` is now `*float[256][256]`, and only allocated & assigned in a `startmap`
  - `width_of[256]` in `struct ft2_font_map_s` is moved to `struct dp_font_s` `width_of_ft2[MAX_FONT_SIZES][256]`
  - Code relative to these are modified accordingly
- Deprecate `r_font_diskcache` as stated in #66

----

**Git log:**

Fix resources waste of fontmap usage worst-cases;
Fix memory waste of improperly designed `struct ft2_font_map_s`; Deprecate `r_font_diskcache`

Signed-off-by: NaitLee <naitli@foxmail.com>

2023-01-30 14:44 UTC, incognico commented
Tested it on my local master build, at least it does not seem to cause any problems so far, though I am not using any CJK languages. Noticed a minor compiler warning:
```
x86_64-w64-mingw32-gcc -static -g1 -Wl,--dynamicbase -Wl,--nxcompat -I../../../.deps/win64/include -L../../../.deps/win64/lib -DSUPPORTIPV6 -MMD   -Wall -Winline -Werror=c++-compat -Wwrite-strings -Wshadow -Wold-style-definition -Wstrict-prototypes -Wsign-compare -Wdeclaration-after-statement -Wmissing-prototypes   -DUSEXMP   -D_FILE_OFFSET_BITS=64 -D__KERNEL_STRICT_NAMES -I../../../    -O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math -c ../../../utf8lib.c -o utf8lib.o
../../../ft2.c: In function 'Font_LoadMap':
../../../ft2.c:1606:56: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 1606 |                         font->name, mapstart->intSize, (unsigned long) mapstart, (unsigned) map_startglyph);
      |                                                        ^
```

2023-01-30 17:05 UTC, NaitLee commented
The warning is fixed and somewhat more correct formatting is used for it.

Near that piece of code are now some notes, to explaining what’s actually going on.

2023-01-31 04:53 UTC, NaitLee commented
May worth looking at #69. Note that the problem isn’t caused by this patch, and we can additionally fix it here.

2023-07-08 06:54 UTC, NaitLee commented
In a commit just now I fixed a problem seen when playing so far (for months), and it’s the only problem.

And it solves #66 and #69 by removing those broken code and marking related cvars as deprecated.

It’s still adviced to give it some test :) just use a CJK language and play around a bit

2023-09-15 11:04 UTC, bones-was-here requested changes

2023-09-16 06:28 UTC, NaitLee commented on gl_draw.c
> +	*/
Uncommented that piece of code in newest commit. (and fixed some language)

Didn’t manage to “optimize” it as for now. It affects performance less than the “big problem”. Probably we shall fix it in a dedicated patch.

2023-09-16 09:24 UTC, bones-was-here commented on gl_draw.c
> +	*/
Ok that helps (significantly reduces the rate of leaking with that test), but we do still leak memory steadily with that test, even with `r_font_disable_incmaps 1` (which seems to slow it down a bit more).

We also still use about 100M more ram even with `r_font_disable_incmaps 1` in Xonotic (at the menu, english language), but Quake seems unaffected by whatever is causing that.

2023-09-16 09:57 UTC, NaitLee commented on gl_draw.c
> +	*/
Probably I don’t have good condition to test it. I see both dp master and current patch commit have memory “jumping” between 200+MiB and 400+MiB. dp stable don’t “jump” at all. (linux64-sdl, English menu)

2023-12-30 12:53 UTC, NaitLee commented
Just now made a change to the `dp_font_s` struct to have related `loadfont` cmdline recorded so that we can compare it with a newer cmd to see whether it actually changed or not, and if not it will do nothing.

So that `alias a "exec font-xolonium.cfg; defer 1 a"; a` no longer leaks repeatedly.

Recording cmdline to a fixed buffer isn't the best, but except that there's no obvious way other than rewriting the entire `LoadFont_f` logic.

A new cvar `r_font_always_reload` is introduced to enable forced reloading.

2023-12-30 13:22 UTC, bones-was-here commented
> Recording cmdline to a fixed buffer isn't the best, but except that there's no obvious way other than rewriting the entire LoadFont_f logic.

How about storing all the arg values (after parsing, so that if an equivalent command is issued it would compare equal even if it has (for example) extra whitespaces) instead of the raw string?  Some might be stored already.

2023-12-30 13:36 UTC, NaitLee commented
The ultimate way to compare "if params are changed" is to compare if every serialized parameters are the same. But the `LoadFont_f` logic is too complex (optional parameters etc. go to different fields all around).

I tried to compare a new `dp_font_s` instance (and raw memory before that) with existing one but had no luck.

That said just serializing argvs to a fixed string is easier, though normally people just re-input the same command as-is, and make changes when they really means to change it.

Any thoughts? I'm lazy to write complex comparison code, lol. it makes code unreadable and unstable.

2024-01-03 21:17 UTC, bones-was-here commented
My thoughts are: if it's a pain don't worry about it, simplicity can be better than overcomplicated perfection.  
Normally these fonts are loaded by a .cfg so its the same cmdline every time.  
Your recent change makes the `exec font-xolonium.cfg` that Xonotic does when resizing the window MUCH faster.  It's not quite as smooth as resizing in Quake (with no font reloading) but it's much nicer :)

Settings for resize testing (kwin no compositing, xorg, nvidia): `vid_width 1440; vid_height 900; vid_fullscreen 0; vid_resizable 1`

---

However... we are still leaking memory.  Your change makes it harder to reproduce, but I was able to by manually running `loadfont user1 fonts/xolonium-regular.otf,fonts/unifont,gfx/vera-sans 4 6 8 10 12 14 16 20 24 28 32 $hud_fontsize` (a line from `font-xolonium.cfg` or some slight variant of it, after doing some resizing.

This doesn't seem to be the fault of your work though: I was able to reproduce it in current `master` more easily than on this branch, by just resizing the window a lot.

Because of that, I'm thinking we could merge this as-is, since it seems we need to fix that leak _anyway_ and in the meantime you've made it less likely to affect people.

2024-01-04 01:33 UTC, bones-was-here commented
Rebased on current master, going to squash a little and then merge

2024-01-04 01:51 UTC, merged